In [1]:
import numpy as np

In [6]:
list1=[1,2,3] # Regular list

In [7]:
list1

[1, 2, 3]

In [4]:
arr=np.array(list1) # Converting to np array

In [5]:
arr

array([1, 2, 3])

In [13]:
np.random.randint(1,10) # Generate a random number between 1,10

1

In [16]:
np.arange(1,10) # Range of values from 1 to 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10,2) # 2 is the step value

array([1, 3, 5, 7, 9])

In [11]:
np.random.randint(1,10,2) # Generate two random values

array([5, 1])

In [12]:
np.random.randint(1,10,(2,4)) # Generate a matrix of random values of size (2,4)

array([[1, 8, 8, 5],
       [4, 6, 1, 7]])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.linspace(1,10,4) # linear space between i and i+1 4 indicates the total number of values

array([ 1.,  4.,  7., 10.])

In [34]:
np.random.seed(101) # Set the seed to generate same set of random values
np.random.randint(1,100,10)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [36]:
arr=np.random.randint(1,100,10) # seed not set values obtained differ everytime

In [37]:
arr

array([50, 84,  9, 30, 60, 35, 45, 73, 20, 11])

In [40]:
arr.max()


84

In [41]:
arr.min()

9

In [42]:
arr.mean()

41.7

In [43]:
arr.argmin()

2

In [44]:
arr.argmax()

1

In [45]:
arr.reshape(2,5)

array([[50, 84,  9, 30, 60],
       [35, 45, 73, 20, 11]])

In [49]:
mat = np.arange(1,101).reshape(10,10)

In [50]:
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [56]:
# To print only the first row
mat[1,:] 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
# To print only first column
mat[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [61]:
mat[3:6,2:5]

array([[33, 34, 35],
       [43, 44, 45],
       [53, 54, 55]])

In [63]:
mat>10 # Check which values in mat are greater than 10

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [64]:
mat[mat>10]

array([ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
        37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
        50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])